env:
  global:
  - secure: Il2SLiC2Z6Z1p2SbgtOV4Ti7RpJckgZDLU69H3lAOHw6HTI8tRNOjNEvgz5AwDoywbaTh3gfgUVZQd9acfj/ZYZjub3YGOrwnnJibJgQNgMOrQfN/JCu+zhkuST9VwJI+N8S3MdfQ5AsDV5P2E90RhK2gKEQ/48BlL5517krefpnM76fVv6n6zWkYrQKi5kGBrvRuoBRlGhlunV7WlF9MKc+g/0V77/KnxVAMIPsOzjtpv56n+9x4U8TidUUcV3h+hymkV1ntwAz65DkKPvO51cWKz6d/ioaX48NW5RoYdO8g6lviWiKyKvt1XfW9WR1ZP4v/1vyl8y712Ff27MGnvKQbGfl6nUXJ4JXl5Lyt821Z0/x+HTUgxYSc24tUqH4Nmf3epg+Lm65bbI+t5WLNxivfXH6D0ZqsQt7VgtAL90GNhMsleGLC8hLB22L3KeAKxKd2fayZd1IyBMLUgMqCwZtFwn78uy3XjGINZjBJ/q/098ooZ2SBbWbE1ax450+OhtOwa1TOQM6kf9PAToMTc+sPzesP9iJ8jwFCzFe/CzeSBjBxPO2RMGMb0KZQxJs3bet3PZx06dsL8A/oX3TQz32SPLl/96/+OhKBOYI19V2EGVbmHXhZzRR3LfxtsKLtVbUuCOca39dPNfN2STmebGsMKYne9H1rcpzo7k3Mn4=
  - secure: moRgOSXUNMeEu5XWtFLUnc3oHuzfo2O2HmJ+monIltAxBKxvXIKB0jb4RtlhulqLg1VmivzZe7bBnXeXQrAMuwRPo7J3omaP+rRWc4MusyCJyNgVCi2fQ6f6kizpsLCJENuA14vp4apLcMmMg10e7m4AnMZSfvA0LxMCGS3hfC7lAOQ5XicanHLODa5NstMxLAPp9s40M9EmfJkwxbzr7KwQtGQXBO7TBgCDmIXjYr+GJS8wfrPGSyP9nVdI1fO1aheEKhdt3g3KWJ54w9C62c/+y2eAQOU3G1dCixmyGLbt/j+fF+Nhyvl+W9Hr+9InnxLAyp5f2vCNXy16F7sSwD78UhXIKHl8y+8yC7dSBw0b1hTnFKa/u7HhC3grZvIW5UI3kdbn2O75SnxZAAcCvIfX6D4aqdl/kTMyZMAb01p+RpVsp++ympuBiH+DQA04Vf9khxbxWmEJnhmrv+SEtmhQljWUP5vw9/Sxn9eQnmnZHRIIVGHtvpLx0/ERpcrI61RTx3sqb2Xa8hM0+QUeajoOyI3jK+vnuO3oQmJgoTyunWmZqZcMXLWt4hi3O6jvAVD0i6E6O2x+t7G5NPIwxj/KHiZP5BHQu4WCoZ3PWdWRC7qfPdneaVS/Q9gApSCibjPyMwRLrXHy4Sl7duLVRnx/qlbJZGbwY6v5bDHknLg=
dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3-pip
    - xclip
language: node_js
services:
- docker
before_install:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- npm install -g codecov && npm install -g istanbul
- pip3 install --user awscli
script:
# - cd client
# - yarn
# - ng test --watch=false
# - ng e2e
# - istanbul cover ./node_modules/karma/bin/karma start -- --single-run --cc
# - codecov -t $CODECOV_TOKEN
after_success:
# - cd ..
- docker-compose build
- docker tag demo-angular-app:0.10.0 826109606486.dkr.ecr.us-east-1.amazonaws.com/demo-angular-app:0.10.0
- eval $(aws ecr get-login --no-include-email)
- docker push 826109606486.dkr.ecr.us-east-1.amazonaws.com/demo-angular-app:0.10.0
- aws ecs register-task-definition --cli-input-json file://ecs-task-def.json
- aws ecs update-service --service demo-angular-app-service --task-definition demo-angular-app-task-def --cluster demo-web-apps


# aws ecs create-cluster --cluster-name "demo-web-apps"
# aws ecr create-repository --repository-name challenge-energy-simply
# aws ecs create-service --load-balancers="targetGroupArn=arn:aws:elasticloadbalancing:us-east-1:826109606486:targetgroup/demo-angular-app-target-group/5cc9af4374d61593,containerName=demo-angular-app,containerPort=80" --cluster demo-web-apps --service-name demo-angular-app-service --task-definition demo-angular-app --desired-count 1 --launch-type "FARGATE" --network-configuration "awsvpcConfiguration={subnets=[subnet-ae51f9a1,subnet-462de70c],securityGroups=[sg-e5eee493],assignPublicIp=ENABLED}" 
# aws ecs create-service --cluster demo-web-apps --service-name demo-angular-app-service --task-definition demo-angular-app --desired-count 1 --launch-type "FARGATE" --network-configuration "awsvpcConfiguration={subnets=[subnet-ae51f9a1,subnet-462de70c],securityGroups=[sg-e5eee493],assignPublicIp=ENABLED}" 
# aws servicediscovery create-private-dns-namespace --name thatbrothacodes.com --vpc vpc-651f841e
# aws servicediscovery create-service --name demo-angular-app-service-discovery --dns-config="NamespaceId=ns-hhldzang26dcrqy7,RoutingPolicy=MULTIVALUE,DnsRecords=[{Type=A,TTL=300}]"
# aws ecs create-service --cli-input-json file://ecs-service-def.json --region us-east-1
# aws route53 change-resource-record-sets --hosted-zone-id Z38IFILMB7YE1W --change-batch file://servicediscovery-def.json

# aws servicediscovery register-instance --service-id srv-5cb3mzukbbsyjxxi --instance-id demo-angular-app.thatbrothacodes.com --attributes=[{AWS_INSTANCE_IPV4:34.239.178.124}]