dist: trusty
sudo: required
addons:
  chrome: stable
  apt:
    sources:
    - deadsnakes
    packages:
      - python3.6
      - python3-pip
language: node_js
services:
  - docker
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g codecov && npm install -g istanbul
  - pip install awscli
script:
  - cd client
  - yarn
  - ng test --watch=false
  - ng e2e
  - istanbul cover ./node_modules/karma/bin/karma start -- --single-run --cc
  - codecov -t $CODECOV_TOKEN
  - ng build --prod
  - cd ..
  - docker-compose build
  - docker tag demo-angular-app:0.4.0 826109606486.dkr.ecr.us-east-1.amazonaws.com/demo-angular-app
