dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
script:
  cd client && yarn && ng test && ng e2e