dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g codecov && npm install -g istanbul && brew install lcov
script:
  - cd client
  - yarn
  - ng test --watch=false
  - ng e2e
  - istanbul cover ./node_modules/karma/bin/karma run --report json  -- -l
  - codecov -t dfb94a19-60a5-428e-a1a6-3f5e5169f2ee
  - ng build --prod
