dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  cd client && yarn && ng test --watch=false && ng e2e && ng build --prod